module Lib (runExercise) where

-- import Exercises.Five.One.Main (main)
-- import Exercises.Five.Two.Main (main)
-- import Exercises.Five.Four.Main (main)
-- import Exercises.Five.Five.Main (main)
-- import Exercises.Five.Six.Main (main)
-- import Exercises.Five.Seven.Main (main)
-- import Exercises.Five.Eight.Main (main)
-- import Exercises.Five.Nine.Main (main)
-- import Exercises.Six.One.Main (main)
-- import Exercises.Six.Two.Main (main)
-- import Exercises.Six.Three.Main (main)
-- import Exercises.Six.Four.Main (main)
-- import Exercises.Six.Five.Main (main)
-- import Exercises.Six.Six.Main (main)
-- import Exercises.Six.Seven.Main (main)
-- import Exercises.Six.Eight.Main (main)
-- import Exercises.Six.Nine.Main (main)
-- import Exercises.Six.Ten.Main (main)
-- import Exercises.Six.Eleven.Main (main)
import Exercises.Six.Twelve.Main (main)

runExercise :: IO ()
runExercise = main
